### PR TITLE
Temp directory customisation

### PR DESCRIPTION
**Pull request by onitake**
Fixes: #56

### CODE REVIEW

**Review by kostyrev — APPROVED** [review]

**Comment by onitake** [comment]
Oh, it looks like I forgot to document this in the readme. Commit coming shortly...

Would you like me to rebase, or will you squash the PR anyway?

**Comment by kostyrev** [comment]
I prefer you to rebase 'cause I don't like gui version of squash and merge

**Comment by onitake** [comment]
All right, here you go. Rebased and squashed into one commit.

**Comment by kostyrev** [comment]
Thank you for your contribution!

**Pull request merged**
