### PR TITLE
Wait for wildfly to start to make sure valid config was produced

### PR DESCRIPTION
**Pull request by kostyrev**
Also success of this wait_for task assures that wildfly is ready to deploy to and no `jboss-cli.sh` commands will fail.
What do you think?
P.S. Don't tag it if it would be merged for I've got some other changes to PR.

### CODE REVIEW

**Comment by inkatze** [comment]
@kostyrev I think this is awesome :) never thought of a way to do this back in the day. I'm gonna wait for your updates before approving this PR, just let me know.

**Comment by kostyrev** [comment]
I meant 'do not git tag it'.
There will be no changes within this PR.
I'll send another one.

**Comment by kostyrev** [comment]
I've decided that waiting for port to open is more elegant solution.

**Comment by kostyrev** [comment]
ping @inkatze

**Review by inkatze — APPROVED** [review]
Looks good!

**Pull request merged**
