### PR TITLE
Custom properties and environment vars

### LINKED ISSUE #19: Accept user supplied JAVA_OPTS and wildfly properties
[wildfly.conf.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.conf.j2) and [wildfly.properties.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.properties.j2) can only manage a very specific subset of the available options. The idea was letting the user edit those files to add more options to those files, but it's a better idea to manage those options with variables.

### PR DESCRIPTION
**Pull request by onitake**
Fixes #19 .

### CODE REVIEW

**Comment by onitake** [comment]
The integration test fails due to a missing docker package.

**Comment by kostyrev** [comment]
Hello @onitake!
Thanks for your contribution!
1) Could you please rebase from master? I've fixed travis build
2) Could you please add new parameters to [host_vars](https://github.com/inkatze/wildfly/blob/master/molecule/default/molecule.yml#L39) or [group_vars](https://github.com/inkatze/wildfly/blob/master/molecule/default/molecule.yml#L53) so that `molecule test` makes sure everything is tested?

**Comment by onitake** [comment]
Ok, I can do that.
Should I add variables to every host_var/OS or just one of them?

**Comment by onitake** [comment]
So, there's test variables now.
However, I have no idea how to verify that they were actually passed into the configuration files - do you know how to do that in molecule?

**Comment by kostyrev** [comment]
Sorry, now I have no resources to complete this PR.  
I'll try this week-end.

**Comment by kostyrev** [comment]
@onitake Please apply [this](https://pastebin.com/LjnXjHFK) patch

**Comment by kostyrev** [comment]
@onitake Could you please squash everything into one commit

**Comment by onitake** [comment]
There you go.

**Review by kostyrev — APPROVED** [review]

**Comment by kostyrev** [comment]
Thank you for your contribution!

**Pull request merged**
