### PR TITLE
New variable to create wildfly home directory (=jboss data dir)

### PR DESCRIPTION
**Pull request by Mageti**
Hello,
I need to have my data dir outside of wildfly directory, so I need to:
- create the directory referenced by `jboss.server.data.dir` in wildfly conf (before wildfly starts)
- change its ownership to wilfly user and group
I could do that as a pre-task, but before creating that directory, I needed the wildfly user and group to be created.
This PR avoids creating 3 pre-tasks just to use a jboss data dir outside of its default path.

### CODE REVIEW

**Comment by Mageti** [comment]
Any news on the PR ?

**Comment by Mageti** [comment]
@inkatze Please could you review my PR ?

**Comment by diego-romero-gusto** [comment]
Hey @Mageti, sorry you had to wait this long for a review.

**Review by diego-romero-gusto — APPROVED** [review]

**Review by diego-romero-gusto — APPROVED** [review]

**Review by inkatze — APPROVED** [review]
Sorry you had to wait this long and thanks for the nudges :)

**Comment by Mageti** [comment]
> Sorry you had to wait this long and thanks for the nudges :)

No problem 🙂
And thanks for your work 👍

**Pull request merged**
